webtalk_init -webtalk_dir C:/Users/drali/Downloads/Pieplined_RISCV/Pieplined_RISCV.sim/sim_1/behav/xsim/xsim.dir/tb_RISCV_demo_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Apr 23 22:25:12 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "63490d13-9c89-4a2d-a491-5e8457219c5d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "4673f415d7df4503be77d61679bb6ab2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Celeron(R) N4020 CPU @ 1.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1094 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "0 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8880_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3386928708 -regid "" -xml C:/Users/drali/Downloads/Pieplined_RISCV/Pieplined_RISCV.sim/sim_1/behav/xsim/xsim.dir/tb_RISCV_demo_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/drali/Downloads/Pieplined_RISCV/Pieplined_RISCV.sim/sim_1/behav/xsim/xsim.dir/tb_RISCV_demo_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/drali/Downloads/Pieplined_RISCV/Pieplined_RISCV.sim/sim_1/behav/xsim/xsim.dir/tb_RISCV_demo_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
